# Don't use DATABASE_URL directly - parse it instead
spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# S3 Bucket
aws.region=${AWS_REGION}
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.bucket=${AWS_BUCKET}
